#!/bin/sh

# Utility script to run the Cashmere sync adviser on the specified arguments.

# Check CASHMERE.
if [ -z "$CASHMERE" ];  then
    echo "please set CASHMERE to the location of your Cashmere installation" 1>&2
    exit 1
fi

exec "$CASHMERE"/cashmere-scripts/cashmere-run -Xmx256M ibis.cashmere.impl.syncrewriter.SyncAdviser "$@"
