#!/bin/sh

# Utility script to run the Cashmere frontend on the specified arguments.

if [ -z "$CASHMERE" ];  then
    echo "please set CASHMERE to the location of your Cashmere installation" 1>&2
    exit 1
fi

java -classpath "$CLASSPATH:$CASHMERE/lib/"'*' ibis.compile.Ibisc "$@"
