#!/bin/bash

. $CASHMERE/scripts/config.bash

. $CASHMERE/scripts/run-cashmere-app-das4

. $CASHMERE/scripts/run-cashmere-app-single-node


INPUT_FILE=$CASHMERE_APP_DIR/raytracer2/scenes/cornell.scn


if [[ ($# -ge 1) && (($1 == "cpu") || ($1 == "gpu")) ]]
then

    if [[ $1 == "cpu" ]]
    then
	nrSamples=1
    else
	nrSamples=400
    fi

    gpu_cpu=$1
    shift

    $CASHMERE/scripts/run-on-nodes.$MACH \
	$CASHMERE_APP_DIR/raytracer2 lib/raytracer2.jar Raytracer \
	4096 2048 $INPUT_FILE $nrSamples $gpu_cpu "$@"

else
    echo "USAGE: $(basename $0) <cpu|gpu>"
    exit 1
fi



