#!/bin/bash

. $CASHMERE/scripts/config.bash

RUN_SCRIPT=$CASHMERE/scripts/run-on-nodes

DIR=raytracer2

INPUT_FILE=$CASHMERE_APP_DIR/raytracer2/scenes/cornell.scn

RUN="Raytracer 16384 8192 $INPUT_FILE"

export CLASSPATH=`./create-class-path $CASHMERE_APP_DIR/$DIR lib/$DIR.jar`

./run-script.x -Dcashmere.closed -Xmx25G \
    -Dcashmere.detailedStats=true -Dibis.server.address=fs0.das4.cs.vu.nl \
    -Dcashmere.queueSteals=false -Dcashmere.ft.naive=true \
    -Dibis.pool.size=1 -Dibis.server.port=$CASHMERE_PORT \
    -Dibis.pool.name=das4.$$ $RUN > FLOPS2
