#!/bin/bash

. $CASHMERE/scripts/config.bash

RUN_SCRIPT=$CASHMERE/scripts/run-fat

O=unoptimized
case "X$1" in
    X)
	;;
    *)
	O="$1"
	;;
esac

DEST=raytracer_result.new.$O
case $O in
optimized)
    DIR=raytracer2_optimized
    ;;
*)
    DIR=raytracer2
    ;;
esac

INPUT_FILE=$CASHMERE_APP_DIR/raytracer2/scenes/cornell.scn

mkdir -p $DEST

RUN="Raytracer 16384 8192 $INPUT_FILE 500 gpu"

( cd ../apps/cashmere/$DIR
  MCL_FILES=raytracer_hd7970.cl,raytracer_cc_2_0.cl ant
)

$RUN_SCRIPT c2050=2 k20=8 hd7970=1 gtx480=10 titan=1 gtx680=1 $CASHMERE_APP_DIR/$DIR lib/$DIR.jar $RUN > $DEST/mix.out 2>&1
mv gantt.data $DEST/gantt-mix.data
mv gantt-thread.data $DEST/gantt-thread-mix.data
