#!/bin/bash


. $CASHMERE/scripts/config.bash
. $CASHMERE/scripts/create_class_path.bash


usage() {
    echo "runCashmereAppDas4 <nrNodes> <basedir> <jar> <class> [args]"
}



runCashmereAppDas4() {
    if [ $# -ge 3 ]
    then
	nrNodes=$1
	shift
	basedir=$1
	shift
	jar=$1
	shift
	class="$1"
	shift
	args=$*

	#prun -np $nrNodes \
	#prun -np $nrNodes -native '-l ngpus=1' \
	#prun -np $nrNodes -native '-l fat,accel=XeonPhi' \
	#prun -np $nrNodes -q "all.q@node001,gpu.q@node009" \
	prun -np $nrNodes -native '-l gpu=GTX480' \
	    CLASSPATH=`createClassPath $basedir $jar` \
	    ./run-script -Dcashmere.closed \
	    -Xmx22G \
	    -Dcashmere.detailedStats=true \
	    -Dibis.server.address=fs0.das4.cs.vu.nl -Dibis.pool.size=$nrNodes \
	    -Dibis.server.port=$CASHMERE_PORT -Dibis.pool.name=das4 $class $args
    else
	usage
    fi
}
