#!/bin/bash

. $CASHMERE/scripts/config.bash

RUN_SCRIPT=$CASHMERE/scripts/run-fat

O=optimized
case "X$1" in
    X)
	;;
    *)
	O="$1"
	;;
esac

DEST=nbody_result.test.$O

mkdir -p $DEST

RUN="NBody -it 3 -gpufactor 4 -min 16384 16777216"

( cd ../apps/cashmere/nbody
  MCL_FILES=nbody_cc_2_0.cl,nbody_xeon_phi.cl,nbody_hd7970.cl ant $O
)

$RUN_SCRIPT hd7970=1 gtx480=10 k20=8 c2050=2 titan=1 gtx680=1 $CASHMERE_APP_DIR/nbody lib/nbody.jar $RUN > $DEST/mix.out 2>&1
mv gantt.data $DEST/gantt-mix.data
mv gantt-thread.data $DEST/gantt-thread-mix.data
