#!/bin/bash

. $CASHMERE/scripts/config.bash

RUN_SCRIPT=$CASHMERE/scripts/run-fat

O=optimized
case "X$1" in
    X)
	;;
    *)
	O="$1"
	;;
esac

DEST=kmeans_result.$O

mkdir -p $DEST

RUN="-Dcashmere.alg=MW KMeans -gpu -gpuJobsPerTask 8 -nPoints 268435456 -nFeatures 4 -nCenters 8192 -iters 3 -nTasks 256"

( cd ../apps/cashmere/kmeans
  MCL_FILES="kmeans_cc_2_0.cl,kmeans_xeon_phi.cl,kmeans_hd7970.cl" ant $O
)

$RUN_SCRIPT hd7970=1 gtx480=10 k20=8 c2050=2 titan=1 gtx680=1 $CASHMERE_APP_DIR/kmeans lib/kmeans.jar $RUN > $DEST/mix.out 2>&1
mv gantt.data $DEST/gantt-mix.data
mv gantt-thread.data $DEST/gantt-thread-mix.data
