#!/bin/sh

# This script can be used for running ibis applications with prun (which
# probably is only available on our own DAS system).

if [ -z "$CASHMERE" ];  then
    echo "please set CASHMERE to the location of your Cashmere installation" 1>&2
    exit 1
fi

if [ -z "$COMMAND" ]; then
    COMMAND="$CASHMERE/cashmere-scripts/cashmere-run"
fi

# SGE destroys path, but saves it in SGE_O_PATH. Reset it.
if [ $USER != hphijma ]
then
    if [ -z "$SGE_O_PATH" ]
    then	:
    else    export PATH="$SGE_O_PATH"
    fi
fi

# Check if user forgot no-panda flag. In that case, filter rank and nhosts.
NHOSTS=`echo $PRUN_HOSTNAMES | awk '{print NF}'`
case "X${1}X$2" in
X${PRUN_CPU_RANK}X$NHOSTS)
    shift
    shift
    ;;
esac

echo I am `hostname`

export LD_PRELOAD=/usr/lib/jvm/java-1.7.0/jre/lib/amd64/libjsig.so

mkdir -p /local/$USER

. "$COMMAND" -Djava.io.tmpdir=/local/$USER -Dibis.implementation=ib "$@" 2>&1 | tee out.${PRUN_CPU_RANK}
